/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kapuk;

import java.sql.Connection;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static kapuk.Dashboard.txt_nota;

/**
 *
 * @author Farid
 */
public class Transaksi1 extends javax.swing.JFrame {

    /**
     * Creates new form Transaksi1
     */
    public Transaksi1() {
        initComponents();
        tampilNama();
        tampilPupuk();
        gkedit();
        input();
    }
    
     public final void input(){
    txt_idTrans.setText(txt_nota.getText());
    txt_idTrans.setEditable(false);
    }
    
    
//    private void batas(){
//    if (txt_namaPlg.equals("umum")){
//    txt_jenis. "Subsidi";
//    }
           
//    }
    
      private void hitung(){
    int harga = Integer.parseInt(txt_idPpk.getText());
    int jumlah = Integer.parseInt(txt_jumlah.getText());
   
    int subTtl  = harga * jumlah;
    txt_subTotal.setText(String.valueOf(subTtl));
    
    }
    
        private void gkedit(){
    txt_idTrans.setEditable(false);
    txt_idPpk.setEditable(false);
    txt_jenis.setEditable(false);
    txt_jumlah.setEditable(false);
    txt_total.setEditable(false);
    txt_subTotal.setEditable(false);
    }
        
         private void kosong(){
    txt_namaPpk.setSelectedItem(null);
    txt_idPpk.setText(null);
    txt_jenis.setText(null);
    txt_jumlah.setText(null);
    txt_subTotal.setText(null);
    }
    
    public void tampilNama(){
    try{
         String sql = "SELECT * FROM pelanggan";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next()){
            txt_namaPlg.addItem(rs.getString("namaPelanggan"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
    }catch(Exception e){
    }
    }
    
    
    public void tampilPupuk(){
    try{
         String sql = "SELECT * FROM pupuk";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next()){
            txt_namaPpk.addItem(rs.getString("Merek"));
            }
            
            rs.last();
            int jumlahdata = rs.getRow();
            rs.first();
    }catch(Exception e){
    }
    }
    
       private void total(){
     try {
            String sql = "SELECT SUM(Sub_total) FROM detail_transaksi WHERE id_transaksi='"+txt_idTrans.getText()+"'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txt_total.setText(rs.getString(1));
                
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cari = new javax.swing.JButton();
        txt_tgl = new com.toedter.calendar.JDateChooser();
        txt_idPlg = new javax.swing.JTextField();
        txt_namaPlg = new javax.swing.JComboBox<>();
        txt_namaPpk = new javax.swing.JComboBox<>();
        txt_cari = new javax.swing.JTextField();
        txt_idTrans = new javax.swing.JTextField();
        txt_jenis = new javax.swing.JTextField();
        txt_idPpk = new javax.swing.JTextField();
        txt_jumlah = new javax.swing.JTextField();
        txt_total = new javax.swing.JTextField();
        txt_subTotal = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        id_kar = new javax.swing.JLabel();
        btn_tambah = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_pupuk = new javax.swing.JButton();
        btn_supp = new javax.swing.JButton();
        btn_karyawan = new javax.swing.JButton();
        btn_pelanggan = new javax.swing.JButton();
        btn_transaksi = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_bayar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/cari.png"))); // NOI18N
        btn_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_cari.setContentAreaFilled(false);
        btn_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cariActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 40, 40));

        txt_tgl.setBackground(new java.awt.Color(152, 135, 101));
        txt_tgl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(txt_tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 200, 40));

        txt_idPlg.setBackground(new java.awt.Color(152, 135, 101));
        txt_idPlg.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_idPlg.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_idPlg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_idPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idPlgActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, 90, 40));

        txt_namaPlg.setBackground(new java.awt.Color(152, 135, 101));
        txt_namaPlg.setForeground(new java.awt.Color(152, 135, 101));
        txt_namaPlg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---" }));
        txt_namaPlg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_namaPlg.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_namaPlgItemStateChanged(evt);
            }
        });
        txt_namaPlg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_namaPlgActionPerformed(evt);
            }
        });
        txt_namaPlg.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txt_namaPlgPropertyChange(evt);
            }
        });
        jPanel1.add(txt_namaPlg, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 140, 40));

        txt_namaPpk.setBackground(new java.awt.Color(152, 135, 101));
        txt_namaPpk.setForeground(new java.awt.Color(152, 135, 101));
        txt_namaPpk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Select---", " " }));
        txt_namaPpk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_namaPpk.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                txt_namaPpkItemStateChanged(evt);
            }
        });
        txt_namaPpk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_namaPpkMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                txt_namaPpkMouseReleased(evt);
            }
        });
        txt_namaPpk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namaPpkKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_namaPpkKeyReleased(evt);
            }
        });
        jPanel1.add(txt_namaPpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 220, 40));

        txt_cari.setBackground(new java.awt.Color(204, 204, 204));
        txt_cari.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_cari.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_cari.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cariActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 210, 40));

        txt_idTrans.setBackground(new java.awt.Color(152, 135, 101));
        txt_idTrans.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_idTrans.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_idTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idTransActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 200, 40));

        txt_jenis.setBackground(new java.awt.Color(152, 135, 101));
        txt_jenis.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_jenis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_jenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jenisActionPerformed(evt);
            }
        });
        jPanel1.add(txt_jenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 220, 220, 40));

        txt_idPpk.setBackground(new java.awt.Color(152, 135, 101));
        txt_idPpk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_idPpk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_idPpk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idPpkActionPerformed(evt);
            }
        });
        jPanel1.add(txt_idPpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, 220, 40));

        txt_jumlah.setBackground(new java.awt.Color(152, 135, 101));
        txt_jumlah.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_jumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jumlahActionPerformed(evt);
            }
        });
        txt_jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_jumlahKeyReleased(evt);
            }
        });
        jPanel1.add(txt_jumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 290, 220, 40));

        txt_total.setBackground(new java.awt.Color(152, 135, 101));
        txt_total.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_totalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 200, 40));

        txt_subTotal.setBackground(new java.awt.Color(152, 135, 101));
        txt_subTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_subTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_subTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_subTotalActionPerformed(evt);
            }
        });
        jPanel1.add(txt_subTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 360, 220, 40));

        txt_harga.setBackground(new java.awt.Color(152, 135, 101));
        txt_harga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_harga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        txt_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_hargaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_harga, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, 220, 40));

        id_kar.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        id_kar.setForeground(new java.awt.Color(255, 255, 255));
        id_kar.setText("ughu");
        id_kar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(id_kar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 20, 130, 40));

        btn_tambah.setContentAreaFilled(false);
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });
        jPanel1.add(btn_tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 420, 70, 40));

        btn_edit.setContentAreaFilled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });
        jPanel1.add(btn_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 420, 70, 40));

        btn_hapus.setContentAreaFilled(false);
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });
        jPanel1.add(btn_hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 420, 60, 40));

        btn_menu.setContentAreaFilled(false);
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 220, 100));

        btn_pupuk.setContentAreaFilled(false);
        jPanel1.add(btn_pupuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 230, 50));

        btn_supp.setContentAreaFilled(false);
        jPanel1.add(btn_supp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 210, 50));

        btn_karyawan.setContentAreaFilled(false);
        jPanel1.add(btn_karyawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 60));

        btn_pelanggan.setContentAreaFilled(false);
        jPanel1.add(btn_pelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 220, 60));

        btn_transaksi.setContentAreaFilled(false);
        jPanel1.add(btn_transaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 230, 60));

        btn_laporan.setContentAreaFilled(false);
        jPanel1.add(btn_laporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 220, 50));

        btn_logout.setContentAreaFilled(false);
        jPanel1.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 650, 230, 60));

        btn_batal.setContentAreaFilled(false);
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 670, 140, 40));

        btn_bayar.setContentAreaFilled(false);
        btn_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bayarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 670, 140, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Pupuk", "Id Pupuk", "Jenis", "Harga Satuan", "Jumlah", "Sub Total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 730, 170));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/07 transaksi(5).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_idTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idTransActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idTransActionPerformed

    private void txt_jenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jenisActionPerformed

    private void txt_idPpkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idPpkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idPpkActionPerformed

    private void txt_jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jumlahActionPerformed

    private void txt_totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_totalActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         if (jTable1.getSelectedRow() == -1){
            if (jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Dalam Tabel");
            }else{
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Diubah");
            }
        }else{
        model.setValueAt(txt_namaPpk.getSelectedItem(), jTable1.getSelectedRow(),0);
        model.setValueAt(txt_idTrans.getText(), jTable1.getSelectedRow(),1);
        model.setValueAt(txt_jenis.getText(),jTable1.getSelectedRow(),2);
        model.setValueAt(txt_harga.getText(), jTable1.getSelectedRow(),3);
         model.setValueAt(txt_jumlah.getText(), jTable1.getSelectedRow(),4);
        model.setValueAt(txt_subTotal.getText(), jTable1.getSelectedRow(),5);
        }
        try {
            String sql = "UPDATE detail_transaksi SET qty= "+txt_jumlah.getText()+", Sub_total ="+txt_subTotal.getText()+" WHERE id_transaksi = '"
                    +txt_idTrans.getText()
                    +"' AND kode_barang = '"+txt_idPpk.getText()+"'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_editActionPerformed

    private void txt_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cariActionPerformed

    private void txt_namaPpkKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaPpkKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPpkKeyReleased

    private void btn_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cariActionPerformed
        // TODO add your handling code here:
            try {
            String sql = "SELECT harga_jual, jenis, Merek FROM pupuk WHERE id_pupuk='"+txt_cari.getText() +"' OR Merek LIKE '%"+txt_cari.getText() +"%'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txt_idPpk.setText(rs.getString(1));
                txt_jenis.setText(rs.getString(2));
                txt_namaPpk.setSelectedItem(rs.getString(3));
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kode Barang Salah!!");
        }
        txt_jumlah.setEditable(true);
    }//GEN-LAST:event_btn_cariActionPerformed

    private void txt_namaPpkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namaPpkKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPpkKeyPressed

    private void txt_namaPpkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_namaPpkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPpkMouseClicked

    private void txt_namaPpkMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_namaPpkMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_namaPpkMouseReleased

    private void txt_namaPpkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_namaPpkItemStateChanged
        // TODO add your handling code here:
        try {
            String sql = "SELECT harga_jual, jenis, id_pupuk FROM pupuk WHERE Merek LIKE '%"+txt_namaPpk.getSelectedItem()+"%'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                txt_harga.setText(rs.getString(1));
                txt_jenis.setText(rs.getString(2));
                txt_idPpk.setText(rs.getString(3));
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Kode Barang Salah!!");
        }
        txt_jumlah.setEditable(true);
    }//GEN-LAST:event_txt_namaPpkItemStateChanged

    private void txt_subTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_subTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_subTotalActionPerformed

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(txt_jumlah.getText().trim().equals("") || txt_namaPpk.getSelectedItem().equals("")){
            JOptionPane.showMessageDialog(null, "Data Yang Dimasukkan Belum Lengkap");
        }else{
        model.addRow(new Object[]{txt_namaPpk.getSelectedItem(),txt_idPpk.getText(),txt_jenis.getText(),txt_idPpk.getText(),
        txt_jumlah.getText(),txt_subTotal.getText()});
        }
        try {
            String sql = "INSERT INTO detail_transaksi VALUES ('"+txt_idTrans.getText()+"','"+txt_idPpk.getText()+"',"+txt_jumlah.getText()+","+txt_subTotal.getText()+")";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void txt_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_hargaActionPerformed

    private void txt_jumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_jumlahKeyReleased
        // TODO add your handling code here:
        int jumlah = Integer.parseInt(txt_jumlah.getText());
        try {
            String sql = "SELECT Stok FROM pupuk WHERE id_pupuk='"+txt_idPpk.getText() +"' OR Merek LIKE '%"+txt_namaPpk.getSelectedItem()+"%'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            if(rs.next()){
                int stok = rs.getInt(1);
                if(stok<jumlah){
                JOptionPane.showMessageDialog(null, "Maaf Stok Tidak Mencukupi");
                kosong();
                }
            }
                
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
        hitung();
        
    }//GEN-LAST:event_txt_jumlahKeyReleased

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        txt_namaPpk.setSelectedItem(model.getValueAt(jTable1.getSelectedRow(),0).toString());
        txt_idTrans.setText(model.getValueAt(jTable1.getSelectedRow(),1).toString());
        txt_jenis.setText(model.getValueAt(jTable1.getSelectedRow(),2).toString());
        txt_harga.setText(model.getValueAt(jTable1.getSelectedRow(),3).toString());
        txt_jumlah.setText(model.getValueAt(jTable1.getSelectedRow(),4).toString());
        txt_subTotal.setText(model.getValueAt(jTable1.getSelectedRow(),5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if (jTable1.getSelectedRow() == -1){
            if (jTable1.getRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Tidak Ada Data Dalam Tabel");
            }else{
            JOptionPane.showMessageDialog(null, "Pilih Data Yang Akan Dihapus");
            }
        }else{
        model.removeRow(jTable1.getSelectedRow());
        }
        try {
            String sql = "Delete from detail_transaksi WHERE id_pupuk= '"+txt_idPpk.getText()+"'AND id_transaksi='"+txt_idTrans.getText()+"'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        kosong();
        total();
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "Delete from transaksi WHERE id_transaksi='"+txt_idTrans.getText()+"'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        this.setVisible(false);
        new Dashboard().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bayarActionPerformed
        // TODO add your handling code here:
        String tampilan = "yyyy-MM-dd";
        SimpleDateFormat fm = new SimpleDateFormat(tampilan);
        String tgl = String.valueOf(fm.format(txt_tgl.getDate()));
        try {
            String sql = "UPDATE transaksi set id_karyawan = '"+id_kar.getText()+"', grand_total =" 
                    +txt_gtotal.getText()+", tgl_penjualan = '"+tgl+"'"+"WHERE nota_penjualan ='"+ txt_nota1.getText()+"'";
            java.sql.Connection conn=(Connection)Konfigurasi.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        this.setVisible(false);
        new nota().setVisible(true);
    }//GEN-LAST:event_btn_bayarActionPerformed

    private void txt_namaPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_namaPlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_namaPlgActionPerformed

    private void txt_namaPlgItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_txt_namaPlgItemStateChanged
        // TODO add your handling code here:
            try{
         String sql = "SELECT * FROM pelanggan where namaPelanggan ='"+txt_namaPlg.getSelectedItem()+"'";
            java.sql.Connection conn=(Connection)Narahubung.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            java.sql.ResultSet rs = pst.executeQuery(sql);
            
            while (rs.next()){
            txt_idPlg.setText(rs.getString("id_pelanggan"));
            }

    }catch(Exception e){
    }
    }//GEN-LAST:event_txt_namaPlgItemStateChanged

    private void txt_namaPlgPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txt_namaPlgPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_namaPlgPropertyChange

    private void txt_idPlgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idPlgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idPlgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_bayar;
    private javax.swing.JButton btn_cari;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_karyawan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_pelanggan;
    private javax.swing.JButton btn_pupuk;
    private javax.swing.JButton btn_supp;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_transaksi;
    private javax.swing.JLabel id_kar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txt_cari;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_idPlg;
    private javax.swing.JTextField txt_idPpk;
    private javax.swing.JTextField txt_idTrans;
    private javax.swing.JTextField txt_jenis;
    private javax.swing.JTextField txt_jumlah;
    private javax.swing.JComboBox<String> txt_namaPlg;
    private javax.swing.JComboBox<String> txt_namaPpk;
    private javax.swing.JTextField txt_subTotal;
    private com.toedter.calendar.JDateChooser txt_tgl;
    private javax.swing.JTextField txt_total;
    // End of variables declaration//GEN-END:variables
}
